### ISSUE TITLE
Are there any semi-supervised collections？

### ISSUE THREAD

**Issue by jamdodot** [M-3LAB/awesome-industrial-anomaly-detection#8]
Are there any semi-supervised collections, such as _MemSeg_?  If I want to read semi-supervised papers, are there any recommendations?  thanks 🙏

**Comment by shirowalker** [comment]
I'm not quite sure if you're referring to using real anomaly data or artificially generated anomaly data when you mention "semi-supervised". Regarding semi-supervised methods using real anomaly data, they are collected in the section 2.3 "More Normal Samples With (Less Abnormal Samples or Weak Labels)". MemSeg is relatively more biased towards unsupervised methods because its anomalies mainly come from artificial method. Similar methods include Draem-a discriminatively trained reconstruction embedding for surface anomaly detection, Cutpaste: Self-supervised learning for anomaly detection and localization, DSR: A dual subspace re-projection network for surface anomaly detection, and Natural Synthetic Anomalies for Self-supervised Anomaly Detection and Localization.

**Comment by jamdodot** [comment]
thank you ！ What I want to know about is MenSeg, which artificially simulates anomalies, but it is based on AE and also uses a memory bank module. Does it mean that semi-supervised (or weakly supervised) can also use some unsupervised components? What is the core difference?

**Comment by shirowalker** [comment]
> thank you ！ What I want to know about is MemSeg, which artificially simulates anomalies, but it is based on AE and also uses a memory bank module. Does it mean that semi-supervised (or weakly supervised) can also use some unsupervised components? What is the core difference?

Currently, unsupervised methods can be mainly divided into two categories: one does not use any anomaly data, while the other, such as MemSeg, uses self-generated anomaly data. The method of using synthetic anomaly data in MemSeg is essentially no different from semi-supervised methods, with the only difference being in the training data. Therefore, overall, semi-supervised methods can use unsupervised components, and only need to replace the synthetic anomaly data with real anomaly data in the training dataset.

**Comment by jamdodot** [comment]
Memseg belongs to the One-Class Classification category, it all uses synthetic anomaly samples for training, so why is this not a full-supervised, synthetic anomaly also have labeled data 😕  If I make changes on Memseg can my method be called a semi-supervised method 😢

**Comment by shirowalker** [comment]
> Memseg belongs to the One-Class Classification category, it all uses synthetic anomaly samples for training, so why is this not a full-supervised, synthetic anomaly also have labeled data 😕 If I make changes on Memseg can my method be called a semi-supervised method 😢

Indeed, MemSeg utilized synthetic data for supervised training. My categorization of supervised and unsupervised methods is mainly based on the type of original dataset used. It is true that our categorization may have some limitations, but the current framework may be more convenient for people to search for relevant papers. Totally, I think it is acceptable to refer to MemSeg as either a supervised or semi-supervised method.

**Comment by shirowalker** [comment]
> thank you ！ What I want to know about is MemSeg, which artificially simulates anomalies, but it is based on AE and also uses a memory bank module. Does it mean that semi-supervised (or weakly supervised) can also use some unsupervised components? What is the core difference?



> thank you ！ What I want to know about is MemSeg, which artificially simulates anomalies, but it is based on AE and also uses a memory bank module. Does it mean that semi-supervised (or weakly supervised) can also use some unsupervised components? What is the core difference?

I'm sorry that I didn't notice the question, it may be because I closed the issue, so please @ me again. Many semi-supervised or weakly supervised methods can utilize unsupervised components, and some relevant papers can be found in section 2.3 of the repository. Personally, I have read "Prototypical Residual Networks for Anomaly Detection and Localization", "Efficient Anomaly Detection with Budget Annotation Using Semi-Supervised Residual Transformer", and "Few-shot defect image generation via defect-aware feature manipulation". These are all excellent works that borrow ideas from unsupervised methods under semi-supervised conditions. If I fail to reply within a day, please feel free to send an email to my mailbox "[liujq32021@mail.sustech.edu.cn](mailto:liujq32021@mail.sustech.edu.cn)".
